name: CD Pipeline



on:
 
  push:   
  
   branches: [ "main" ]


jobs:

  build:

    runs-on: [ubuntu-12.04]
    
    steps:

    - name: Checkout source repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: build project
      run: mvn clean install -DskipTests

    #- name: Configure AWS credentials
     # uses: aws-actions/configure-aws-credentials@v2
      #with:
       # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        #aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
       # aws-region: us-east-1
    
      # uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
         DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
         DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the docker image
      run: docker build -t devopstest2024/ecs-poc-repo .

    - name: Publish the Docker image into docker hub
      run: docker push devopstest2024/ecs-poc-repo:latest

  deploy:
   needs: build
  
   runs-on: TR-GitHub-ECS
   steps: 

     - name: Pull image from docker hub
       run: docker pull devopstest2024/ecs-poc-repo:latest

     - name: Delete Old docker container
       run: docker rm -f ecs-poc-repo-container || true
       
     - name: run docker container   
     - run: sudo docker run -d -p 8080:8080 --name ecs-poc-repo-container devopstest2024/ecs-poc-repo:latest
