name: CD Pipeline

on:

 
  push:   
  
   branches: [ "main" ]


jobs:

  build:

    runs-on: ["self-hosted"]
    
    steps:

    - name: Checkout source repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: build project
      run: mvn clean install -DskipTests

      # uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
         DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
         DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the docker image
      run: docker build -t devopstest2024/ashu-gh-repo .

    - name: Publish the Docker image into docker hub
      run: docker push devopstest2024/ashu-gh-repo:latest

  deploy:
   needs: build
  
   runs-on: TR-GitHub-ECS
   steps: 

     - name: Pull image from docker hub
       run: docker pull devopstest2024/ashu-gh-repo:latest

     - name: Delete Old docker container
       run: docker rm -f ashu-gh-repo-container || true
       
     - name: run docker container   
     - run: sudo docker run -d -p 8080:8080 --name ashu-gh-repo-container devopstest2024/ashu-gh-repo:latest
