name: CD Pipeline


on:
 
  push:   
  
   branches: [ "main" ]

jobs:

  build:

    runs-on: TR-GitHub-ECS
    
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
    
      # uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
         DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
         DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Pull Docker image
      run: sudo docker pull devopstest2024/ecs-poc-repo:latest


    - name: Delete Old docker container
      run: sudo docker rm -f ecs-poc-repo-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name ecs-poc-repo-container devopstest2024/ecs-poc-repo
