
name: CI Pipeline


on:
  push:
    branches: [ "main" ]

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  
jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
      -name: Install Docker
      run: DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
           curl jq build-essential libssl-dev libffi-dev python3 python3-venv python3-dev python3-pip
           
    - name: Install Docker
      run: docker build -t devopstest2024/ecs-poc-repo .
    - name: Push to Dockerhub
      run: docker push devopstest2024/ecs-poc-repo:latest
    - name: Pull Docker image
      run: sudo docker pull devopstest2024/ecs-poc-repo:latest
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name ecs-poc-repo-container devopstest2024/ecs-poc-repo
